version: '3.8'

services:
  contextual-scholar:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - CHROMA_PERSIST_DIRECTORY=/app/chroma_db
    volumes:
      - ./data:/app/data
      - chroma_data:/app/chroma_db
    depends_on:
      - neo4j
    networks:
      - contextual-scholar-network

  neo4j:
    image: neo4j:5.14
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - contextual-scholar-network

volumes:
  neo4j_data:
  neo4j_logs:
  chroma_data:

networks:
  contextual-scholar-network:
    driver: bridge
